apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-exp-dep
  labels:
    app: hpa-example
spec:
  selector:
    matchLabels:
      app-name: hpa-example
  template:
    metadata:
      labels:
        app-name: hpa-example
    spec:
      containers:
      - name: hpa-example-container
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: 200m