---
kind: DaemonSet
apiVersion: extensions/v1beta1
# apiVersion: apps/v1beta2
# kind: Deployment
metadata:
  name: glusterfs
  labels:
    glusterfs: daemonset
  annotations:
    description: GlusterFS DaemonSet
    tags: glusterfs
spec:
  # replicas: 2
  selector:
    matchLabels:
      glusterfs: pod
  template:
    metadata:
      name: glusterfs
      labels:
        glusterfs: pod
        glusterfs-node: pod
    spec:
      containers:
      - image: gluster/gluster-centos:latest
        imagePullPolicy: Always
        name: glusterfs
        env:
        - name: GB_GLFS_LRU_COUNT
          value: "15"
        - name: TCMU_LOGDIR
          value: "/var/log/glusterfs/gluster-block"
        - name: MACHINE_UUID
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CACHESIZE
          value: 3072M
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        # - name: glusterfs-heketi
        #   mountPath: "/var/lib/heketi"
        # - name: glusterfs-run
        #   mountPath: "/run"
        # - name: glusterfs-lvm
        #   mountPath: "/run/lvm"
        # - name: glusterfs-etc
        #   mountPath: "/etc/glusterfs"
        # - name: glusterfs-logs
        #   mountPath: "/var/log/glusterfs"
        # - name: glusterfs-config
        #   mountPath: "/var/lib/glusterd"
        - name: glusterfs-dev
          mountPath: "/dev"
        # - name: glusterfs-misc
        #   mountPath: "/var/lib/misc/glusterfsd"
        - name: glusterfs-cgroup
          mountPath: "/sys/fs/cgroup"
          readOnly: true
        # - name: glusterfs-ssl
        #   mountPath: "/etc/ssl"
        #   readOnly: true
        # - name: kernel-modules
        #   mountPath: "/usr/lib/modules"
        #   readOnly: true
        - name: cache-volume
          mountPath: /glustercache #resize use mount -o remount,size=3072m /glustercache
        securityContext:
          capabilities: {}
          privileged: true
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 40
          exec:
            command:
            - "/bin/bash"
            - "-c"
            - systemctl status glusterd.service
          periodSeconds: 25
          successThreshold: 1
          failureThreshold: 50
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 40
          exec:
            command:
            - "/bin/bash"
            - "-c"
            - systemctl status glusterd.service
          periodSeconds: 25
          successThreshold: 1
          failureThreshold: 50
      volumes:
      # - name: glusterfs-heketi
      #   emptyDir: {}
      #   # hostPath:
      #   #   path: "/var/lib/heketi"
      # - name: glusterfs-run
      # - name: glusterfs-lvm
      #   emptyDir: {}
      #   # hostPath:
      #   #   path: "/run/lvm"
      # - name: glusterfs-etc
      #   emptyDir: {}
      #   # hostPath:
      #   #   path: "/etc/glusterfs"
      # - name: glusterfs-logs
      #   emptyDir: {}
      #   # hostPath:
      #   #   path: "/var/log/glusterfs"
      # - name: glusterfs-config
      #   emptyDir: {}
      #   # hostPath:
      #   #   path: "/var/lib/glusterd"
      - name: glusterfs-dev
        hostPath:
          path: "/dev"                                    ## must use this
      # - name: glusterfs-misc
      #   emptyDir: {}
      #   # hostPath:
      #   #   path: "/var/lib/misc/glusterfsd"
      - name: glusterfs-cgroup
        hostPath:
          path: "/sys/fs/cgroup"                          ## must use this
      # - name: glusterfs-ssl
      #   emptyDir: {}
      #   # hostPath:
      #   #   path: "/etc/ssl"
      # - name: kernel-modules
      #   emptyDir: {}
      #   # hostPath:
      #   #   path: "/usr/lib/modules"
      - name: cache-volume
        emptyDir:
          medium: "Memory"