apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app-name: nginx
  template:
    metadata:
      labels:
        app-name: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-pv-storage
      volumes:
        - name: nginx-pv-storage
          persistentVolumeClaim:
            claimName: nginx-pvc #be care of this indent