apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app-name: nginx
  template:
    metadata:
      labels:
        app-name: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/etc/sec"
          name: scv
          readOnly: true
      volumes:
        - name: scv
          secret:
            secretName: mysecret